#!/bin/bash
#push this script to /usr/bin/adb
#and change the value of ADB_PATH to the real adb command path

ADB_PATH="/usr/local/android-sdk-linux/platform-tools/adb"

fake_adb_parent=$(cd $(dirname $0); pwd)
fake_adb_name=$(basename $0)
fake_abs_path="$fake_adb_parent/$fake_adb_name"

real_adb=${ADB_PATH-adb}
real_adb_name=$(basename ${real_adb})
if [ "X${real_adb_name}" == "X${real_adb}" ];then
    real_abs_path=$(which adb)
else
    fake_adb_parent=$(cd $(dirname ${real_adb}); pwd)
    real_abs_path="$fake_adb_parent/$fake_adb_name"
fi

if [ "X${fake_abs_path}" == "X${real_abs_path}" ]; then
    echo "The call for adb command will cause indefinite loop"
    exit 1
fi
if [ "X$1" == "Xconnect" ] || [ "X$1" == "Xdisconnect" ];then
    sleep 3
    flock /var/lock/lava-adb.lck ${real_abs_path} "$@"
    rm -f /var/lock/lava-adb.lck
else
    ${real_abs_path} "$@"
fi
